openapi: 3.0.3
info:
  title: NewsAPI
  description: newsapi.com
  version: 1.0.0
servers:
- url: https://newsapi.org/v2
paths:
  /top-headlines:
    get:
      parameters:
      - name: country
        in: query
        description: The 2-letter ISO 3166-1 code of the country you want to get headlines for
        required: true
        schema:
          type: string
      - name: category
        in: query
        description: he category you want to get headlines for
        required: false
        schema:
          type: string
      - name: sources
        in: query
        description: TA comma-seperated string of identifiers for the news sources or blogs you want headlines from. Use the /top-headlines/sources endpoint to locate these programmatically or look at the sources index.
        required: false
        schema:
          type: string
      - name: q
        in: query
        description: Keywords or a phrase to search for.
        required: false
        schema:
          type: string
      - name: pageSize
        in: query
        description: The number of results to return per page (request). 20 is the default, 100 is the maximum.
        required: false
        schema:
          type: integer
      - name: page
        in: query
        description: Use this to page through the results if the total results found is greater than the page size.
        required: false
        schema:
          type: integer
      - name: apiKey
        in: query
        description: API key
        required: true
        schema:
          type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsResponse'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    NewsResponse:
      type: object
      $ref: '#/components/schemas/NewsArray'
    NewsArray:
      properties:
        status:
          type: "string"
        totalResults:
          type: "number"
        articles:
          type: array
          items:
            $ref: '#/components/schemas/News'
    News:
      # required:
      #   - "imperial"
      #   - "metric"
      properties:
        source:
          type: object
          $ref: '#/components/schemas/Source'
        author:
          type: "string"
        title:
          type: string
        description:
          type: string
        url:
          type: string
        urlToImage:
          type: string
        publishedAt:
          type: string
        content:
          type: string
    Source:
      properties:
        id:
          type: "string"
        name:
          type: "string"
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          maximum: 600
          minimum: 100
          type: integer
